export { default as About } from './About'
export { default as Blog } from './Blog'
export { default as Home } from './Home'
export { default as Products } from './Products'
export { default as SingleProduct } from './SingleProduct'
export { default as Page404 } from './Page404'
export { default as SignUp } from './SignUp'
